# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/transposition.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_transposition(object):
    def setupUi(self, transposition):
        transposition.setObjectName("transposition")
        transposition.resize(800, 422)
        self.centralwidget = QtWidgets.QWidget(transposition)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 240, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 60, 581, 87))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 340, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 180, 581, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(180, 230, 581, 87))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 340, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 20, 291, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        transposition.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(transposition)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        transposition.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(transposition)
        self.statusbar.setObjectName("statusbar")
        transposition.setStatusBar(self.statusbar)

        self.retranslateUi(transposition)
        QtCore.QMetaObject.connectSlotsByName(transposition)

    def retranslateUi(self, transposition):
        _translate = QtCore.QCoreApplication.translate
        transposition.setWindowTitle(_translate("transposition", "Transposition Cipher"))
        self.label_4.setText(_translate("transposition", "Cipher Text:"))
        self.pushButton.setText(_translate("transposition", "Encrypt"))
        self.label_3.setText(_translate("transposition", "Key:"))
        self.label_2.setText(_translate("transposition", "Plain Text:"))
        self.pushButton_2.setText(_translate("transposition", "Decrypt"))
        self.label.setText(_translate("transposition", "TRANSPOSITION CIPHER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    transposition = QtWidgets.QMainWindow()
    ui = Ui_transposition()
    ui.setupUi(transposition)
    transposition.show()
    sys.exit(app.exec_())
